import Head from "next/head";
import { useSession } from "next-auth/react";
import { Box, Text } from "@primer/react";

export default function Home() {
  const { data } = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box
          sx={{
            margin: "0 auto",
            width: "800px",
            p: 4,
            backgroundColor: "canvas.inset",
            borderRadius: 6,
            color: "fg.default",
          }}
          as="pre"
        >
          {JSON.stringify(data, null, 2)}
        </Box>
      </main>
    </>
  );
}
