import { useEffect, useState } from "react";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { Octokit } from "octokit";
// use stable octokit

export default function Home() {
  const { data } = useSession();
  const [loading, setLoading] = useState(true);
  const [notifications, setNotifications] = useState<any[]>([]);
  const [octokit, setOctokit] = useState<Octokit>();

  useEffect(() => {
    if (data?.accessToken) {
      setOctokit(new Octokit({ auth: data.accessToken }));
      setLoading(false);
    }
  }, [data]);

  async function getNotifications() {
    const { data } = await octokit?.request("GET /notifications");
    setNotifications(data);
    console.log(data);
  }

  useEffect(() => {
    if (octokit) {
      getNotifications();
    }
  }, [octokit]);

  if (loading) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <pre>{JSON.stringify(data, null, 2)}</pre>
        {notifications.map((notification) => (
          <div key={notification.id}>
            <h4>{notification.subject.title}</h4>
            <p>{notification.repository.name}</p>
            <p>{notification.repository.owner.login}</p>
            <p>{notification.updated_at}</p>
            <p>{notification.reason}</p>
            <a href={notification.url}>{notification.url}</a>
          </div>
        ))}
      </main>
    </>
  );
}
